# Generated by Django 5.1.4 on 2024-12-16 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название тура')),
                ('duration', models.IntegerField(verbose_name='Длительность тура (дней)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена тура')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='countries.country', verbose_name='Страна тура')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='hotels.hotel', verbose_name='Отель тура')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
    ]
